CheeseMVC/Models/Cheese.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.Models
{
    public class Cheese
    {
        public int CheeseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        private static int nextId = 1;

        /*
        public Cheese(string name, string description)
        {
            Name = name;
            Description = description;
        }
        */
        public Cheese() {
            CheeseId = nextId;
            nextId++;
        }
    }


}

CheeseMVC/Models/CheeseData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CheeseMVC.Models
{
    public class CheeseData
    {
        static private List<Cheese> cheeses = new List<Cheese>();

        //GetAll Method
        public static List<Cheese> GetAll()
        {
            return cheeses;
        }

        //Add Method
        public static void Add(Cheese cheese)
        {
            cheeses.Add(cheese);
        }

        //Remove Method
        public static void Remove(int id)
        {
            cheeses.Remove(GetById(id));
        }

        //GetById Method
        public static Cheese GetById(int id)
        {
            return cheeses.SingleOrDefault(x => x.CheeseId == id);
        }
    }
}

CheeseMVC/Models/ErrorViewModel.cs
using System;

namespace CheeseMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CheeseMVC/Controllers/CheeseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CheeseMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace CheeseMVC.Controllers
{
    public class CheeseController : Controller
    {
        //static means this property is available to any code in the class
        //static private List<string> Cheeses = new List<string>();
        //static private List<Cheese> Cheeses = new List<Cheese>();

        public IActionResult Index()
        {
            ViewBag.cheeses = CheeseData.GetAll();
            return View();
        }

        public IActionResult Add()
        {

            return View();
        }

        [HttpPost]
        [Route("/Cheese/Add")]
        public IActionResult NewCheese(Cheese newCheese)
        {
            //Add the new cheese to my existing cheeses 
            /*Model binding means we don't have to create a new cheese like this. But you have to
             * have a default constructor in the model for model binding to work
             * Cheese newCheese = new Cheese
            {
                Description = description,
                Name = name
            };
            */

            CheeseData.Add(newCheese);

            /*Another way:
            Cheese newCheese = new Cheese();
            newCheese.Description = description;
            newCheese.Name = name;
            */

            return RedirectToAction(actionName: nameof(Index));
        }

        /*
        public IActionResult Index2 ()
        {
            //This will render the Index view above
            return View("Index");
        }
        */

        public IActionResult Remove()
        {
            ViewBag.title = "Remove Cheeses";
            ViewBag.cheeses = CheeseData.GetAll();
            return View();
        }

        [HttpPost]
        public IActionResult Remove(int[] cheeseIds)
        {
            foreach (int cheeseId in cheeseIds)
            {
                CheeseData.Remove(cheeseId);
            }
            return Redirect("/Cheese");
        }
    }
}

CheeseMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CheeseMVC.Models;

namespace CheeseMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CheeseMVC/Views/Cheese/Add.cshtml
@{

}

<h1>Add Cheese</h1>

<form method="post">
    <label for="name">Name: </label>
    <input type="text" name="name" />
    <label for="description">Description: </label>
    <input type="text" name="description" />
    <input type="submit" value="Add Cheese" />
</form>

CheeseMVC/Views/Cheese/Index.cshtml
@{
    
}

<h1>My Cheeses</h1>

<p><a asp-controller="Cheese" asp-action="Add">Add Cheese</a></p>

@if (ViewBag.cheeses.Count == 0)
{
    <p>No cheeses yet!</p>
}

<table class="table">
    <!--precede all C# code with the @@ symbol-->
    <tr>
        <th>Name</th>
        <th>Description</th>
    </tr>
    
    @foreach (var cheese in ViewBag.cheeses)
    {
        <tr>
            <td>@cheese.Name</td>
            <td>@cheese.Description</td>
        </tr>
    }
</table>

CheeseMVC/Views/Cheese/Remove.cshtml
<h1>@ViewBag.title</h1>

<form method="post">
    @foreach (var cheese in ViewBag.cheeses)
    {
        <input type="checkbox" name="cheeseIds" id="@cheese.CheeseId" value="@cheese.CheeseId" />
        <label for="@cheese.CheeseId">@cheese.Name</label>
        <br />
    }

    <input type="submit" value="Remove Selected Cheese(s)" />
</form>

CheeseMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CheeseMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CheeseMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CheeseMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cheese" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cheese" asp-action="Add">Add</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CheeseMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>